"""BRD DOCX Generator — converts assembled BRD JSON to Word document."""
from docx import Document
from docx.shared import Pt, RGBColor, Cm, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from datetime import datetime


def _hr(doc):
    p = doc.add_paragraph()
    pr = p._p.get_or_add_pPr()
    b = OxmlElement('w:pBdr')
    bot = OxmlElement('w:bottom')
    bot.set(qn('w:val'),'single'); bot.set(qn('w:sz'),'4')
    bot.set(qn('w:space'),'1');    bot.set(qn('w:color'),'DDDDDD')
    b.append(bot); pr.append(b)


def generate_docx(brd: dict, path: str = "BRD.docx") -> str:
    doc = Document()
    for s in doc.sections:
        s.top_margin=Cm(2.5); s.bottom_margin=Cm(2.5)
        s.left_margin=Cm(3);  s.right_margin=Cm(3)

    # Title
    tp = doc.add_paragraph(); tp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    tr = tp.add_run(brd.get("title","Business Requirements Document"))
    tr.font.size=Pt(22); tr.font.bold=True
    tr.font.color.rgb=RGBColor(0x1a,0x1a,0x2e)

    sp = doc.add_paragraph(); sp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sr = sp.add_run("Business Requirements Document — NEXUS AI Agent")
    sr.font.size=Pt(11); sr.font.color.rgb=RGBColor(0x66,0x66,0x88)

    doc.add_paragraph(); _hr(doc); doc.add_paragraph()

    # Metadata table
    tbl = doc.add_table(rows=5, cols=2); tbl.style='Table Grid'
    for i,(l,v) in enumerate([
        ("Title",   brd.get("title","BRD")),
        ("Version", brd.get("version","1.0")),
        ("Status",  brd.get("status","Draft")),
        ("Date",    datetime.now().strftime("%B %d, %Y")),
        ("Generated by", "NEXUS AI Agent"),
    ]):
        tbl.rows[i].cells[0].text = l
        tbl.rows[i].cells[1].text = str(v)
        tbl.rows[i].cells[0].paragraphs[0].runs[0].font.bold = True

    doc.add_paragraph(); _hr(doc); doc.add_paragraph()

    SECTIONS = [
        ("executive_summary",         "1. Executive Summary"),
        ("business_objectives",       "2. Business Objectives"),
        ("scope",                     "3. Project Scope"),
        ("functional_requirements",   "4. Functional Requirements"),
        ("non_functional_requirements","5. Non-Functional Requirements"),
        ("stakeholders_decisions",    "6. Stakeholders & Key Decisions"),
        ("risks_constraints",         "7. Risks, Constraints & Dependencies"),
        ("feature_prioritization",    "8. Feature Prioritization"),
        ("timeline_milestones",       "9. Timeline & Milestones"),
    ]

    for key, title in SECTIONS:
        content = brd.get("sections", {}).get(key, "")
        if not content: continue

        h = doc.add_heading(level=1); h.clear()
        r = h.add_run(title)
        r.font.size=Pt(14); r.font.bold=True
        r.font.color.rgb=RGBColor(0x1a,0x1a,0x2e)
        doc.add_paragraph()

        for line in content.strip().split("\n"):
            line = line.rstrip()
            if not line: doc.add_paragraph(); continue
            if line.startswith(("- ","• ","* ")):
                p=doc.add_paragraph(style="List Bullet"); p.add_run(line[2:]).font.size=Pt(10.5)
            elif line[:2] in [f"{n}." for n in range(1,20)] or (len(line)>2 and line[0].isdigit() and line[1] in '.)'):
                p=doc.add_paragraph(style="List Number"); p.add_run(line[2:].strip()).font.size=Pt(10.5)
            elif line.startswith(("FR-","NFR-")):
                p=doc.add_paragraph(); r2=p.add_run(line)
                r2.font.bold=True; r2.font.size=Pt(10.5)
                r2.font.color.rgb=RGBColor(0x22,0x44,0x88)
            elif line.endswith(":") and len(line)<60:
                p=doc.add_paragraph(); r2=p.add_run(line)
                r2.font.bold=True; r2.font.size=Pt(11)
            else:
                p=doc.add_paragraph(); p.add_run(line).font.size=Pt(10.5)

        _hr(doc); doc.add_paragraph()

    # Footer
    fp = doc.add_paragraph(); fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fr = fp.add_run(f"Generated by NEXUS AI Agent  ·  {datetime.now().strftime('%B %d, %Y %H:%M')}")
    fr.font.size=Pt(9); fr.font.italic=True
    fr.font.color.rgb=RGBColor(0xAA,0xAA,0xAA)

    doc.save(path)
    print(f"[DOCX] Saved: {path}")
    return path
